# Generated by Django 5.2.3 on 2025-06-14 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], default='Petrol', max_length=20)),
                ('kilometers', models.PositiveIntegerField()),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=20)),
                ('color', models.CharField(default='White', max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discounted_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('body_style', models.CharField(default='Convertible', max_length=50)),
                ('engine', models.CharField(default='3.4L Mid-Engine V6', max_length=100)),
                ('drivetrain', models.CharField(default='Rear Wheel Drive', max_length=50)),
                ('exterior_color', models.CharField(default='Lime Gold Metallic', max_length=50)),
                ('interior_color', models.CharField(default='Agate Grey', max_length=50)),
                ('doors', models.PositiveIntegerField(default=2)),
                ('passengers', models.PositiveIntegerField(default=2)),
                ('vin', models.CharField(blank=True, max_length=100, unique=True)),
                ('fuel_mileage_city', models.PositiveIntegerField(default=20)),
                ('fuel_mileage_highway', models.PositiveIntegerField(default=28)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used')], default='Brand New', max_length=50)),
                ('owners', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty', models.CharField(default='3 Years Limited', max_length=100)),
                ('short_description', models.TextField(blank=True, null=True)),
                ('long_description', models.TextField(blank=True, null=True)),
                ('main_image', models.ImageField(upload_to='cars/')),
                ('gallery_image_1', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('gallery_image_2', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('gallery_image_3', models.ImageField(blank=True, null=True, upload_to='cars/')),
                ('gallery_image_4', models.ImageField(blank=True, null=True, upload_to='cars/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('customer_need', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listings.car')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cars', to='listings.category'),
        ),
    ]
