# Generated by Django 5.2.3 on 2025-06-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rent_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per day/week/month for rent', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='condition',
            field=models.CharField(choices=[('Brand New', 'Brand New'), ('Used', 'Used'), ('Semi New', 'Semi new'), ('Damaged', 'Damaged'), ('Any', 'Any')], default='Brand New', max_length=50),
        ),
    ]
